### ISSUE TITLE
bullmq-otel tried to access tslib, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

### ISSUE THREAD

**Issue by dobesv** [taskforcesh/bullmq-otel#9]
In the built outputs in `dist/cjs/index.js` it does `require('tslib')`.  However, `tslib` is declared only as a `devDependency` in the project.

![Image](https://github.com/user-attachments/assets/d41ac23c-c4c7-4008-a801-fc47399602d8)

**Comment by joemckie** [comment]
Until this is fixed, it can be worked around by adding the following into either your `.yarnrc.yml` or `pnpm-workspace.yaml` file:

```yml
# .yarnrc.yml
packageExtensions:
  "bullmq-otel@*":
    dependencies:
      tslib: ^2.0.0
```

```yml
# pnpm-workspace.yaml
packageExtensions:
  bullmq-otel:
    dependencies:
      tslib: ^2.0.0
```
